Migration to v1.0.0
jeromegn/docker.cr pull request #7
Opened 2021-06-08 13:25 UTC by hholst80

- Require Crystal `>= 1.0.0`.
- Remove `spec2` shard.
  Not maintained. Replaced with stdlib Spec.
- Require `json_mapping` shard.

2021-06-08 13:52 UTC, hholst80 commented
We also need a git tag for v0.2.0 I have not added that. There are some other PRs that you might want to include in v0.2.0 as well

2021-06-08 14:00 UTC, jeromegn commented
I think we need version.cr to reflect the new version number too.

2021-06-08 17:02 UTC, jeromegn requested changes
Please update version.cr too

2021-06-10 20:49 UTC, jeromegn approved these changes

2021-06-10 20:49 UTC, merged